image: node:latest

cache:
  paths:
    - node_modules/

deploy_develop:
  stage: deploy
  environment: develop
  only:
    - master
  script:
    - npm install -g firebase-tools
    - npm install
    - npm run build
    - firebase use --token $FIREBASE_TOKEN default
    - firebase deploy -m "Pipeline $CI_PIPELINE_ID, build $CI_BUILD_ID" --non-interactive --token $FIREBASE_TOKEN